### ISSUE TITLE
About Metal-doped semiconductor

### ISSUE THREAD

**Issue by makhlouf** [epfl-theos/koopmans#215]
Dear developers,
I plan to calculate electronic and optical properties of Metal-doped semiconductors
I already installed and tested the koopmans code on my machine without problem, 
but since koopmans has limitations with regard to metals (according to the documentation),
I wonder if we can do doping of semiconductors with metals.
Thanks in advance

**Comment by elinscott** [comment]
Dear @makhlouf , thanks for your question. In order to answer your question, it is worth being very specific about what these limitations are. Specifically, Koopmans functionals require you to be able to separate the occupied and empty manifolds at the level of DFT. In general, this means that _your system needs to have a band gap as predicted by DFT_. If it has a band gap, then the Koopmans method can be applied.

Of course, the other factor you might want to consider is the computational cost, because depending on the dopant concentrations you are interested in, the supercell you need to model might become very large and the cost of running Koopmans calculations might become prohibitive.

I hope this helps!

**Comment by elinscott** [comment]
I am going to close this issue now. If in the future you have similar questions to this one, please post them on our [google group](https://groups.google.com/g/koopmans-users) where we discuss questions such as these (and where others can easily see these discussions). We try to limit GitHub Issues to reporting bugs with the `koopmans` code.
